apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: yourdomain-com-tls #putting here domain name is optional, its just to recollect that the certificate is for xyz domain.  
spec:
  secretName: yourdomain-com # specify where the obtained certificate should be stored.
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: yourdomain.com ## your domain name is required here
  dnsNames:
    - yourdomain.com ## your domain name is required here
    - www.yourdomain.com ## your domain name is required here